version: '3.8'
services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:stable
    command: /home/suwayomi/startup_script.sh
    ports:
      - "4567:4567"
      - "8080:8080"
    environment:
      - TERM=xterm
      - TZ=Europe/Madrid
    volumes:
      - /home/carri/suwayomi/data:/home/suwayomi/.suwayomi
      - /home/carri/suwayomi/manga:/manga

    restart: unless-stopped